AddReplicableComponent("icey2_skiller")
AddReplicableComponent("icey2_skill_summon_pact_weapon")
AddReplicableComponent("icey2_skill_shield")
AddReplicableComponent("icey2_skill_parry")
AddReplicableComponent("icey2_versatile_weapon")
